export const LAYOUT_PARAMS = {
  navHeight: 50,
  tabHeight: 40,
  sideWidth: 240,
  sideCollapsedWidth: 64,
  sideMenuCollapsedWidth: 48,
  sideMenuCollapsedIconSize: 22,
  mixSideWidth: 80,
  mixSideCollapsedWidth: 48,
  mixSideDrawerWidth: 200,
  contentPadding: 20,
  footHeight: 50,
  backTopRight: 50,
  backTopBottom: 50,
  backTopVisibilityHeight: 450,
  settingsDrawerWidth: 330,
  settingsButtonRight: 40,
  settingsButtonBottom: 100,
}
