import defaultAvatar from '~/assets/default-avatar.jpg'

export const defaultUserList = [
  {
    id: 1,
    username: 'zhangsan229',
    name: '张三',
    avatar: defaultAvatar,
    phone: '66666666666',
    email: 'dajiahao@163.com',
    roleId: 1,
    createTime: new Date(),
    updateTime: new Date(),
  },
  {
    id: 2,
    username: 'lisi33',
    name: '李四',
    avatar: defaultAvatar,
    phone: '66666666666',
    email: 'dajiahao@163.com',
    roleId: 1,
    createTime: new Date(),
    updateTime: new Date(),
  },
  {
    id: 3,
    username: 'wangwu88',
    name: '王五',
    avatar: defaultAvatar,
    phone: '66666666666',
    email: 'dajiahao@163.com',
    roleId: 2,
    createTime: new Date(),
    updateTime: new Date(),
  },
  {
    id: 4,
    username: 'liming',
    name: '李明',
    avatar: defaultAvatar,
    phone: '66666666666',
    email: 'dajiahao@163.com',
    roleId: 2,
    createTime: new Date(),
    updateTime: new Date(),
  },
  {
    id: 5,
    username: 'gang777w',
    name: '小刚',
    avatar: defaultAvatar,
    phone: '66666666666',
    email: 'dajiahao@163.com',
    roleId: 3,
    createTime: new Date(),
    updateTime: new Date(),
  },
]
